### ISSUE TITLE
 Enforce signed requests

### ISSUE THREAD

**Issue by leereichardt** [Andreyco/Instagram-for-PHP#19]
Are you going to support Instagrams signed requests?

**Comment by Andreyco** [comment]
Do you mean "per-request signature"? Well, this would be good, definitely. Will take a look at this, PR would definitely speed things up.

**Comment by leereichardt** [comment]
To be honest, I have no idea how to create a Pull Request on github. I've made some quick (untested) edits to the file that should make it work though.

If you give me a brief rundown on how to do a PR, then I can do that, else if you'd prefer me just to upload the file here, let me know.

**Comment by Andreyco** [comment]
That's awesome!

Please, see https://help.github.com/articles/fork-a-repo/
First important section is **Fork an example repository** - that way you create your own copy (fork) of this repository. You can skip following section - _Keep your fork synced_, since you will be starting with up-to-date repository.
When you are done editing your repository, commit your changes and push them to Github. Then, you will find "Create Pull Request" button in your repo page ;)

**Comment by leereichardt** [comment]
Cool, thanks for that guide. It's all done and a PR has been created

**Comment by Andreyco** [comment]
@leereichardt thanks a lot for PR, good work! I will add Laravel support in a moment, and possibly will update one method naming. Will release another version right away.

**Comment by Andreyco** [comment]
Version 4.1.0 released, @leereichardt  thanks for your help!
